### ISSUE TITLE
Clarify what part of the API belongs to userspace or BPF-space

### ISSUE THREAD

**Issue by laarmen** [uccidibuti/rebpf#6]
Sadly I've had to rewrite my BPF program in C as the Rust compiler wouldn't generate code that the verifier in my kernel version can handle, but I still very much intend to use this crate for the userspace side of things.

However, as it stands it's not very clear which part of the `rebpf` crate purely belongs to the BPF side of things, which part should be used for a userspace loader, and which should be used for interop (that'd be mostly the enums, I guess).

Have I missed something ?

**Comment by uccidibuti** [comment]
I'm worried about your problem in kernel side (maybe is there a bug in rebpf?), Did you try to compile with a recent version of Rust compiler? Note I've found two days ago a little bug in your latest PR [xsk map](https://github.com/uccidibuti/rebpf/commit/5d92fdee0464ce6eeb2f8a3d89602f76d1f3a573).

I agree with you that is not clear understand which functions/structs  in rebpf are kernel side or userspace side. Currently helpers.rs, map.rs and mostly enums/structs in lib.rs should be used to write bpf programs (kernel side) and all functions/structs/enums in lib.rs for usersapce side.  I think to fix this problem moving in a new module common.rs all structs/enums used from both side (kernel and userspace), and specifying in the documentation for each module if is a "kernel mod" or "userspace mod", what do you think about my suggestion?

**Comment by laarmen** [comment]
No, the problem didn't have anything to do with rebpf, it was with the code that was emitted by rustc for various slice operations that I have to do in my use case (which is using CpuMap, I just added the other two for completeness, hence the copy-paste bug you found :-) ).

Basically, on newer versions (with LLVM 9) in some cases it emits the LLVM intrinsic `bcmp` which is supposed to be implemented by the underlying platform. Of course, that isn't the case for BPF. There's a crate that implements the intrinsics in Rust for platforms that need it, but the generated code uses loops (which makes sense from their point of view) and even with constant propagation and inlining, those loops don't get unrolled.

On older versions, I had the same kind of problems. Basically, as soon as you call out to code outside of your immediate control, there's a risk that the codegen will do stuff that's actually forbidden by the underlying VM.

Again, not saying writing BPF programs in Rust isn't feasible, it's just that in my case it didn't work out as quickly as I wished, so I took the easy way out :)

**Comment by laarmen** [comment]
About the suggestion, I'd go as far as having one specific *explicit* namespace (with submodules within if it makes sense) for each platform, and having common code near the top level. It might be a bit heavy-handed, but at least you don't have to get to the documentation to find out if a particular piece of code might be used.

For instance, it'd be nice to have the `map` types defined both in BPF and userspace (with of course differing implementations, which means you'd have

```
src/
    map.rs // Contains the traits for common map operations, i.e. Redirect
    bpf/
        map.rs // Contains the actual CpuMap struct and its implementation blocks for the traits
    userspace/
        map.rs // Userspace CpuMap, with its own data structure, etc...
```

In the same vein, I'd have XdpAction and XdpMd in the `bpf` module, as they don't make sense outside of this specific execution context.

**Comment by uccidibuti** [comment]
If I compile with llvm < llvm 9 also my stupid bpf programs are rejected from verifier but with llvm 9 they work correctly, I have only tried only stupid program, I will try to do more complicated bpf programs  (for instance using loop macro) to understand and try to fix the verifier rejected problems (maybe llvm 10 can solve your problems)..

About code restyle I will try to accept you suggestion, I will do this tonight..

**Comment by uccidibuti** [comment]
I have restructured rebpf modules as follows:
```
src/
      lib.rs (library entry point where modules are exposed)
      libbpf.rs: contains all libbpf structs/functions.
      helpers.rs: contains all bpf helper functions.
      bpf/ : contains all high-level api for bpf programs
             mod.rs
             map.rs
      userspace/ : contains all high-level api for userspace bpf loader programs
                 mod.rs
      errors.rs
      interface.rs
      utils.rs      
```
At this point it's possible create bpf and userspace high-level api built on top of libbpf.rs, helpers.rs (without using unsafe libbpf-sys crate).
Note1: I haven't created src/maps.rs, src/userspace/maps.rs beacuse currently I haven't implemented userspace high-level maps api but feel free to create src/userspace/maps.rs file and move src/bpf/maps traits into src/maps.rs.
Note2: I have created some macros in src/bpf/maps.rs that impl new, Lookup and Redirect to avoid code repetitions.

**Comment by laarmen** [comment]
Yep, seen it, already working on it 😋

Your macros don't play well with rustfmt, I hope you don't mind if I
rewrite them? I've added a dose of type safety in there as well, too. I was
in the middle of drafting the macros for the userspace maps when my partner
reminded me that I ought to clock off, so the PR will have to wait until
tomorrow.

Le lun. 27 avr. 2020 à 03:43, Lorenzo Vannucci <notifications@github.com> a
écrit :

**Comment by uccidibuti** [comment]
Feel free to restyle/improve/change my macros, I've just noticed this crate on reddit rust community https://crates.io/crates/duplicate and maybe we can use it..
